### ISSUE TITLE
issues with obtaining guild avatar and user avatar since discord once again has been upgrading there api / js

### ISSUE THREAD

**Issue by ghost** [Tslimshady99/Bubble-Plugin-Discord-API#1]
issues with obtaining guild avatar and user avatar since discord once again has been upgrading their api / js 

- look into this please?

**Comment by ghost** [comment]
hello @Tslimshady99 think you could look into this please!!!

**Comment by ghost** [comment]
cant really do anything with out this being fixed :'( this one is the best on the market atm for bubble as well hope 🙏to hear back from you!

**Comment by Tslimshady99** [comment]
I plan to redo the plug-in once I get some time to work on it.

**Comment by Tslimshady99** [comment]
> cant really do anything with out this being fixed :'( this one is the best on the market atm for bubble as well hope 🙏to hear back from you!

This has been fixed
